### PR TITLE
Clean up examples

### PR DESCRIPTION
**Pull request by meskio**
* Let's use the pattern 'ok, res = sdclient.operation()'
* Add python3 support.
* Clean up some pep8 errors.

This should fix the test errors.

### CODE REVIEW

**Comment by meskio** [comment]
@davideschiera I think I fixed the CI errors, but I'm not sure how to run them to check.

**Comment by davideschiera** [comment]
Yeah, it's very unfortunate :-(

Let me see if I can run the test suite locally at least...

**Comment by davideschiera** [comment]
The script seems to be working now.

I see several "prettified" lines. Are you using a linter by any chance? It'd be great to add a basic linting configuration so that everybody could use the same style without worrying much about it. We can discuss this separately from this PR though ;-)

I'll merge the changes. Hopefully no surprises this time! Thanks!

**Comment by davideschiera** [comment]
Few were missing:

https://github.com/draios/python-sdc-client/commit/5ecf3046907943c85286d280e8e8bfb151124bc5
https://github.com/draios/python-sdc-client/commit/2563d62d8d5a2580bdc09b383eee67007322356a

I think it'd make sense to update all the examples, eg. there are still things like:

```
#
# Post the event
#
res = sdclient.add_email_notification_recipient(email)

#
# Return the result
#
if res[0]:
    print 'Recipient added successfully'
else:
    print res[1]
    sys.exit(1)
```

**Comment by meskio** [comment]
For linting I'm using [flake8](http://flake8.pycqa.org/en/latest/), it gives me warnings on my editor (using vim with [ale](https://github.com/w0rp/ale/)). Mostly what flake8 does is to highlight [pep8](https://www.python.org/dev/peps/pep-0008/) errors. I have disabled few errors (E501,E711,E712,W503) and I try to keep the code out of the others.

How do you envision the linting being integrated? Like some recommendations in the README? Or like some travis linting checks?


I'll open another pull-req fixing the rest of the examples. I have fixed the ones used by the tests, and I didn't notice that was more.

**Pull request merged**
