### PR TITLE
Add policy priorities

### PR DESCRIPTION
**Pull request by mstemm**
Changes to support new Sysdig Secure APIs for policy ordering.

### CODE REVIEW

**Comment by mstemm** [comment]
I believe the test failures are due to changes in our demo environment. The secure parts of the test, which use a different environment, are passing.

@cecilpang and/or @ret2libc could you take a look to see if the use of the apis seem reasonable?

**Comment by ret2libc** [comment]
I didn't run it, but the use of the APIs seems fine!

**Comment by philrz** [comment]
@mstemm, yes, I've had to fix this failing test before. I think it usually fails when someone removes or does a shutdown/start on a managed host in the demo environment, resulting in a changed IP address. In the past I've been able to fix it by logging into the demo account and seeing what hosts are currently being monitored and change to the new hostname in the `.travis.yml`.

It might be tedious, but I'd like to fix the failing test. I have the login and password of what used to be the user attached to this, but when I logged in just now it had zero hosts being monitored, or at least that was the case under the default team. There's tons of other teams, and each is going to have its own token. I don't recall how to dig up the secret setting that becomes the `$DEMO_KUBE_API_TOKEN` in `.travis.yml`, but if we had that, we could at least reconfirm which login is attached to that and see what options we might have. If you have info on that, please follow up with me on Slack because this is a public issues repo and we don't need to be giving out credentials here. :)

**Comment by mstemm** [comment]
Yeah, it's that the account changed. I'm going to switch it to the specific account I have set up for the secure side of tests (represented by PYTHON_SDC_TEST_API_TOKEN).

**Comment by mstemm** [comment]
@phil could you look at the last 2 commits, which update the unit tests to use the python testing account and also allow multiple copies to be run at once without stepping over each other?

**Comment by philrz** [comment]
I guess strictly speaking, people who were running these examples out-of-the-box expecting positional command-line args will be broken & have to to adapt to the new `getopt` approach. But that seems a minor inconvenience. On the whole your changes look like a great improvement, so, looks good to me.

**Pull request merged**
