### PR TITLE
IBM Cloud IAM Support

### PR DESCRIPTION
**Pull request by PatrickDuncan**
We would prefer users to authenticate themselves with IAM instead of the Sysdig token when using an IBM Cloud Monitoring with Sysdig instance. 

Example program:
Usage: `./examples/dashboard_ibm_cloud.py`
```shell
./examples/dashboard_ibm_cloud.py $ingest_url $apikey $guid
```

```python
from sdcclient import IbmAuthHelper, SdcClient

url = 'https://us-south.monitoring.cloud.ibm.com'
apikey = # ...
guid = # ...
ibm_headers = IbmAuthHelper.get_headers(url, apikey, guid)
sdclient = SdMonitorClient(sdc_url=url, custom_headers=ibm_headers)

json_res = sdclient.get_dashboards()
print(json_res)
```

### CODE REVIEW

**Comment by davideschiera** [comment]
Hi @PatrickDuncan!

Thanks for the help here, and sorry for the late reply!

I took a look at the proposed changes, and talked with @alexgallotta to fill me in with more context about it. I like the direction, I think we can try to make it more generic to keep the IBM specific changes more independent, while adding more flexibility to the "common" codebase. The main reason for it is that this way we can keep the base classes targeting a generic Sysdig server, while allowing the flexibility of customizing the authentication as you need it.

Here few suggestions I'd like to propose:

1. Add "custom headers" to base classes (`_SdcCommon`, `SdMonitorClient`, etc.) instead of IBM-specific object. Here's a code snippet to clarify:

```
# sdcclient/_common.py

def __init__(self, token="", sdc_url='https://app.sysdigcloud.com', ssl_verify=True, custom_headers=None):
    self.hdrs = {'Content-Type': 'application/json', 'Authorization': 'Bearer ' + self.token }
    merge(
        {'Content-Type': 'application/json', 'Authorization': 'Bearer ' + self.token },
        custom_headers) # merge 2 dictionaries
```


2. Create "helper" function will all the IBM-specific logic to define the HTTP headers you need. The code is mostly what you put in `sdcclient/_ibmcloud.py`, here's a revised option to clarify the "separation of concerns":

```
class IbmAuthHelper:
    @staticmethod
    def get_headers(api_key, guid, url):
        return {
            'Authorization': IbmAuthHelper._get_iam_token(api_key, guid, url),
            'IBMInstanceID': guid
        }

    def _get_token_fetch_url(url):
        IAM_ENDPOINT = {
            'stage': 'iam.test.cloud.ibm.com',
            'prod': 'iam.cloud.ibm.com'
        }

        if '.test.' in url:
            env_url = self.IAM_ENDPOINT['stage']
        else:
            env_url = self.IAM_ENDPOINT['prod']

    def _get_iam_token(api_key, guid, url):
        env_url = IbmAuthHelper._get_token_fetch_url(url)
        response = requests.post(
            'https://' + env_url + '/identity/token',
            data={
                'grant_type': 'urn:ibm:params:oauth:grant-type:apikey',
                'response_type': 'cloud_iam',
                'apikey': api_key
            },
            headers={
                'Accept': 'application/json'
            })
        if response.status_code == 200:
            return response.json()['access_token']
        else:
            response.raise_for_status()

```


3. Lastly, split the configuration in 2 steps: 1) get IBM auth tokens, 2) instantiate Sysdig client class. Example:

```
ibm_headers = IbmAuthHelper.get_headers(APIKEY, GUID, INGEST_URL)
sdclient = SdMonitorClient(sdc_url=INGEST_URL, custom_headers=ibm_headers)
```


Hope this makes sense, let me know if anything doesn't look quite right, I'll be also happy to chat live about it.

Thanks again!

**Comment by PatrickDuncan** [comment]
@davideschiera Thanks for the review, it made a lot of sense.

I left the `IbmAuthHelper` class in `sdcclient/` because all the imported classes are there and subfolder/sibling folder imports in Python is not very.. pleasant

**Comment by PatrickDuncan** [comment]
Hey @davideschiera, is there an ETA on when this will be merged? Users are waiting to use it

**Comment by davideschiera** [comment]
@PatrickDuncan sorry, thanks for reminding me... Done! Thanks for the help!

**Pull request merged**
